import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import 'bootstrap/dist/css/bootstrap.min.css';

import {useEffect, useState} from 'react';
import { Container, Col, Row } from 'react-bootstrap';

import BookList from './components/book-list';
import Form from "./components/form";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [books, setBooks] = useState();
  const [selectedBook, setSelectedBook] = useState(null);

  function createBook() {};

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Container>
          <Row>
            <Col xs="3">
              <BookList list={books} newBook={createBook} selected={selectedBook} click={(id) => setSelectedBook(id)}/>
            </Col>
            <Col>
              <Form/>
            </Col>
          </Row>
        </Container>
      </main>
    </>
  );
}
